# Generated by Django 3.1.3 on 2023-03-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsumury', '0002_auto_20230329_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploadfile/'),
        ),
    ]
