# Generated by Django 3.1.3 on 2023-03-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsumury', '0003_summary_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
